trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  repositories:
  - repository: templates
    type: github
    name: Dshahi14/Central
    endpoint: github.com_Dshahi14

stages:
- stage: 'Build'
  jobs:
  - template: build.yml@templates

- stage: 'DevDeploy'
  dependsOn: ['Build']
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - template: 
    parameters:
     WebAppName: 'WebApp-Dev'

- stage: 'SITDeploy'
  dependsOn: ['Dev']
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - template: 
    parameters:
     WebAppName: 'WebApp-SIT'